name: PDF Processing Pipeline

on:
  push:
    paths:
      - 'DATA/raw_pdfs/**'
  pull_request:
    paths:
      - 'DATA/raw_pdfs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  process-pdfs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create DATA directories
      run: |
        mkdir -p DATA/raw_pdfs
        mkdir -p DATA/embeddings
        touch DATA/raw_pdfs/.gitkeep
        touch DATA/embeddings/.gitkeep
        
    - name: Process PDFs
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python -c "from pdf_processor import PDFProcessor; processor = PDFProcessor(); processor.process_pdfs()"
        
    - name: Commit processed files
      run: |
        git config --local user.email "kunaldmohare@gmail.com"
        git config --local user.name "Mohare786-Kunal"
        git add DATA/embeddings/ DATA/raw_pdfs/.gitkeep DATA/embeddings/.gitkeep
        git commit -m "Update PDF embeddings and metadata" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: ${{ github.ref }}
        force: true 